---
- name: restart tailscaled
  systemd:
    name: tailscaled
    state: restarted
  when: not (disable_handlers | default(false))

- name: reload systemd
  systemd:
    daemon_reload: true
  when: not (disable_handlers | default(false))